name: genesis-test
version: 0.0.1.0
category: Other
synopsis: Opinionated bootstrapping for Haskell web services.
description: Opinionated bootstrapping for Haskell web services.
maintainer: Alexis King <lexi.lambda@gmail.com>
copyright: 2017 CJ Affiliate by Conversant
license: ISC
github: cjdev/genesis

extra-source-files:
- CHANGELOG.md
- package.yaml
- stack.yaml

ghc-options: -Wall
default-extensions:
- ConstraintKinds
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators

library:
  dependencies:
  - base                   >= 4.9 && < 5
  - genesis                == 0.0.1.0
  - hspec
  - hspec-expectations     >= 0.7
  - lifted-base
  - monad-control          >= 1 && < 2
  - monad-logger           >= 0.3.10
  - monad-persist          >= 0.0.1.2 && < 1
  - persistent-postgresql  >= 2.5 && < 3
  - transformers
  - transformers-base
  source-dirs: library

tests:
  genesis-test-test-suite:
    dependencies:
    - base
    - envparse
    - genesis
    - genesis-test
    - hspec
    - monad-logger
    - monad-persist
    - persistent-template
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
