name: genesis
version: 0.0.1.0
category: Other
synopsis: Opinionated bootstrapping for Haskell web services.
description: Opinionated bootstrapping for Haskell web services.
maintainer: Alexis King <lexi.lambda@gmail.com>
copyright: 2017 CJ Affiliate by Conversant
license: ISC
github: cjdev/genesis

extra-source-files:
- CHANGELOG.md
- package.yaml
- stack.yaml

ghc-options: -Wall
default-extensions:
- ConstraintKinds
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TypeApplications
- TypeOperators

library:
  dependencies:
  - base                   >= 4.9.0.0 && < 5
  - directory              >= 1.2.7.0
  - envparse               >= 0.3.0 && < 1
  - file-embed             >= 0.0.10 && < 1
  - filepath
  - monad-control          >= 1.0.0.0 && < 2
  - monad-logger           >= 0.3.10
  - monad-persist          >= 0.0.1.0 && < 1
  - persistent             >= 2.5 && < 3
  - persistent-postgresql  >= 2.5 && < 3
  - persistent-template    >= 2.5 && < 3
  - resource-pool
  - template-haskell       >= 2.11.0.0 && < 2.12
  - text
  - text-conversions       >= 0.2.0 && < 1
  source-dirs: library

tests:
  genesis-test-suite:
    dependencies:
    - base
    - genesis
    - hspec
    - monad-control
    - monad-logger
    - monad-persist
    - persistent-sqlite
    - persistent-template
    - text
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
